### ISSUE TITLE
Bug: Squeak hangs when I cursor is moved while holding Ctrl

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/WindowAcrobatics#67]
I can reproduce this issue on Squeak5.2 and Squeak5.3alpha: Open Squeak, install the latest master of Window Acrobatics and move your cursor while holding Ctrl pressed. On my machine (Win 10), this leads to an immediate hang of Squeak.

Currently, I am not able to terminate the hanging process by `Alt + .`, but using Squeak5.2, @CodeZeilen has been able to locate the problem in the key handling mechanisms of WA.

I am going to provide a pull request that turns the problem off.

**Comment by codeZeilen** [comment]
The new PR fixes the issue for now. However, the proper solution would be to add a WA-specific object as a capture filter to the current world. Something along the lines of:

```Smalltalk
Project current world addKeyboardCaptureFilter: (...)
```
